// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ArsenalService provides Wails bindings for the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCommand adds a command to a group
 * @param {string} groupKey
 * @param {string} cmd
 * @param {string} description
 * @param {string} output
 * @param {string} note
 * @param {string[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function AddCommand(groupKey, cmd, description, output, note, tags) {
    return $Call.ByID(2914892267, groupKey, cmd, description, output, note, tags);
}

/**
 * AddGroup creates a new group
 * @param {string} key
 * @param {string} name
 * @param {string} icon
 * @param {string} description
 * @returns {$CancellablePromise<void>}
 */
export function AddGroup(key, name, icon, description) {
    return $Call.ByID(4096155277, key, name, icon, description);
}

/**
 * DeleteCommand removes a command from a group
 * @param {string} groupKey
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCommand(groupKey, id) {
    return $Call.ByID(1460250133, groupKey, id);
}

/**
 * DeleteGroup removes a group
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteGroup(key) {
    return $Call.ByID(3216577103, key);
}

/**
 * GetCommands returns all commands data
 * @returns {$CancellablePromise<models$0.CommandsFile | null>}
 */
export function GetCommands() {
    return $Call.ByID(694388991).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfig returns current config
 * @returns {$CancellablePromise<models$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(2408235115).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetGroups returns just the groups map
 * @returns {$CancellablePromise<{ [_: string]: models$0.Group }>}
 */
export function GetGroups() {
    return $Call.ByID(2586710137).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * HasConfig checks if app is configured
 * @returns {$CancellablePromise<boolean>}
 */
export function HasConfig() {
    return $Call.ByID(3535615407);
}

/**
 * InitializeDefault sets up ~/.nuke-arsenal with default data if no config exists
 * Returns the data path (existing or newly created)
 * @returns {$CancellablePromise<string>}
 */
export function InitializeDefault() {
    return $Call.ByID(2686057934);
}

/**
 * Search searches across all groups
 * @param {string} query
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function Search(query) {
    return $Call.ByID(2444019599, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SetDataPath saves the data path and loads it
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetDataPath(path) {
    return $Call.ByID(2313679926, path);
}

/**
 * UpdateCommand updates an existing command
 * @param {string} groupKey
 * @param {number} id
 * @param {string} cmd
 * @param {string} description
 * @param {string} output
 * @param {string} note
 * @param {string[]} tags
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCommand(groupKey, id, cmd, description, output, note, tags) {
    return $Call.ByID(2602717567, groupKey, id, cmd, description, output, note, tags);
}

// Private type creation functions
const $$createType0 = models$0.CommandsFile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.Group.createFrom;
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = $models.SearchResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
